name: Docker image create and push to DockerHub

on:
  # push:
  #   branches: [ main ]
  pull_request:    
    branches: [ main ]  # only for PR to main
  workflow_dispatch:
    
env:
  NAMESPACE: default  # kubernetes namespace
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Build and push
      uses: docker/build-push-action@v2
      with:        
        tags: |
          enriquecatala/fastapi-helloworld:latest
          enriquecatala/fastapi-helloworld:${{ steps.date.outputs.date }}

        # build on feature branches, push only on main branch
        push: ${{ github.ref == 'refs/heads/main' }}
        #push: true

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    # - uses: azure/aks-set-context@v1
    #   with:
    #       creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
    #       resource-group: '${{ secrets.RESOURCE_GROUP_NAME }}'
    #       cluster-name: '${{ secrets.CLUSTER_NAME }}'
    #   id: login
    # - uses: Azure/k8s-deploy@v1.4
    #   with:
    #     namespace: ${{ env.NAMESPACE  }}
    #     action: deploy
    #     manifests: |
    #       manifests/deployment.yaml
    #       manifests/service.yaml
    #     images: |
    #       enriquecatala/fastapi-helloworld:${{ steps.date.outputs.date }}
        